#!/bin/bash

echo "🚀 QUICK CLOUDINARY SETUP"
echo "========================="
echo ""
echo "Bước 1: Tạo Cloudinary account (miễn phí)"
echo "👉 Truy cập: https://cloudinary.com/users/register_free"
echo ""
echo "Bước 2: Lấy credentials"
echo "👉 Sau khi đăng ký, vào: https://console.cloudinary.com/console"
echo "👉 Copy: Cloud Name, API Key, API Secret"
echo ""
echo "Bước 3: Tạo file .env"
echo "👉 Tạo file .env trong thư mục gốc với nội dung:"
echo ""
echo "# Copy và paste vào file .env:"
echo "DATABASE_URL=your_database_url_here"
echo "CLOUDINARY_CLOUD_NAME=your_cloud_name_here"
echo "CLOUDINARY_API_KEY=your_api_key_here"
echo "CLOUDINARY_API_SECRET=your_api_secret_here"
echo ""
echo "Bước 4: Restart server"
echo "👉 Ctrl+C để stop server"
echo "👉 npm run dev để start lại"
echo ""
echo "✅ Sau khi setup xong, upload ảnh sẽ thành công!"
echo "📱 Test bằng cách upload ảnh trên profile page"
echo ""
echo "🔍 Check logs để xem:"
echo "- ✅ Cloudinary upload successful"
echo "- ❌ Cloudinary not configured (nếu chưa setup)"
echo ""
echo "💡 File .env.example đã có template sẵn!"